events{
}

http{
    include mime.types;

    upstream backend-servers{
        server localhost:8000;
        server localhost:8002;
        
    }

    server{
        listen 80;
        server_name localhost;

        location /{
            proxy_pass http://localhost:3000;
        }

        location /api{
            proxy_pass http://backend-servers;
        }
    }
}